-- Add IVA fields to Order table
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "ivaPerc"  DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "ivaValor" DECIMAL(10,2)    NOT NULL DEFAULT 0;
