-- Customer: desconto de revendedor
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "taxId" TEXT;

-- Order: campos de desconto
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "descontoPerc"  DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "descontoValor" DECIMAL(10,2)    NOT NULL DEFAULT 0;
